version: '2.4'

services:
  postgres:
    image: postgres:10.5
    ports:
      - '5432'
    # /host for ad-hoc transfers in/out of container
    # /data for DB data itself
    volumes:
      - './data/host:/host'
      - './data/postgres:/var/lib/postgresql/data'

  api:
    build: .
    command: node --inspect=[::]:9229 code/main.js
    restart: always
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/app
    links:
      - postgres
